package a40Exception_Handling;

public class cException_by_try_catch_block {

	public static void main(String[] args) {
		
		System.out.println("Program Started");
		
		int a = 10;
		int b = 0;
		
		int result = 0;
		
		try {
			result = a / b;
		}catch(ArithmeticException ae)
		{
			System.out.println(ae.toString());
		}
	
		System.out.println(result);
		
		System.out.println("Program Ended");
	}


}
